*&---------------------------------------------------------------------*
*& Report  ZWM_R_PALET_ICERIK
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT ZWM_R_PALET_ICERIK.

TABLES:VEKP, VEPO, MARA.
TYPE-POOLS: SLIS.
DATA: GT_FIELDCAT_LIST1 TYPE SLIS_T_FIELDCAT_ALV,
      GT_FIELDCAT_LIST2 TYPE SLIS_T_FIELDCAT_ALV,
      GT_FIELDCAT_LIST3 TYPE SLIS_T_FIELDCAT_ALV.

DATA : BEGIN OF GT_LIST1 OCCURS 0,
         MATNR       LIKE VEPO-MATNR, "malzeme numarası
         COUNT_KUTU  LIKE VEPO-VEMNG,  "kutu sayısı
         TOTAL_KUTU  LIKE VEPO-VEMNG,  "toplam miktar
         BRGEW       LIKE VEKP-BRGEW,  "tek bir malzemeye ait birim brut agirlik kg
         TOTAL_BRGEW LIKE VEKP-BRGEW,  "toplam kg
       END OF GT_LIST1.
DATA : BEGIN OF GT_LIST2 OCCURS 0 ,

         EXIDV LIKE VEKP-EXIDV,  "TAŞIMA BİRİMİ
         MATNR LIKE MARA-MATNR, "MALZEME
         VEMNG LIKE VEPO-VEMNG,  "K.İÇ AD
         BRGEW LIKE VEKP-BRGEW,  "kg
         AENAM LIKE VEKP-AENAM,  "kullanıcı
         AEDAT LIKE VEKP-AEDAT,  "okutulduğu tarih

       END OF GT_LIST2.


DATA : BEGIN OF GT_LIST3 OCCURS 0,
         LGNUM       LIKE VEKP-LGNUM, "DEPO KODU
         DESCRIPTION LIKE VEPO-VEMNG,  "AÇIKLAMA!!!!!!!!!!!!!!!!
         STATUS      LIKE VEKP-STATUS,  "DURUM!!!!!!!!!!!!!!
         PLT_NO      LIKE VEKP-EXIDV,
       END OF GT_LIST3.


SELECTION-SCREEN BEGIN OF BLOCK BLK1. "seçim kriterleri
PARAMETERS PALET_NO TYPE VEKP-EXIDV . " todo:palet filtresi koyulacak
SELECTION-SCREEN END OF BLOCK BLK1.

START-OF-SELECTION.

  PERFORM TABLOLARI_DOLDUR.
  PERFORM ALANKATALOGU_OLUSTUR.
  PERFORM TABLOLARI_GOSTER.


FORM TOP_OF_PAGE.
  DATA: LT_HEADER TYPE SLIS_T_LISTHEADER,
        LS_HEADER TYPE SLIS_LISTHEADER.
  LS_HEADER-TYP  = 'H'.
  LS_HEADER-KEY  = ".
  LS_HEADER-INFO = 'REUSE_ALV_EVENTS_GET Örneği'.
  APPEND LS_HEADER TO LT_HEADER.
  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = LT_HEADER
      I_LOGO             = 'ENJOYSAP_LOGO'.
ENDFORM.


FORM TABLOLARI_DOLDUR .

  SELECT PLT~EXIDV
         PLT~LGNUM
         PLD~VEMNG
         PLT~STATUS
    FROM   VEKP AS PLT
INNER JOIN VEPO AS PLD ON PLT~VENUM = PLD~VENUM
    INTO CORRESPONDING FIELDS OF TABLE GT_LIST3
    WHERE PLT~EXIDV = PALET_NO
 GROUP BY PLT~EXIDV PLT~LGNUM PLD~VEMNG PLT~STATUS.

  LOOP AT GT_LIST3.
    GT_LIST3-PLT_NO = PALET_NO.
    MODIFY GT_LIST3.
  ENDLOOP.

  SELECT KTU~EXIDV
         KTD~MATNR
         KTD~VEMNG
         MAR~BRGEW
         KTU~AENAM
         KTU~AEDAT
    FROM   VEKP AS PLT
INNER JOIN VEPO AS PLD ON PLT~VENUM = PLD~VENUM
INNER JOIN VEKP AS KTU ON PLD~UNVEL = KTU~VENUM
INNER JOIN VEPO AS KTD ON KTU~VENUM = KTD~VENUM
INNER JOIN MARA AS MAR ON KTD~MATNR = MAR~MATNR
    INTO CORRESPONDING FIELDS OF TABLE GT_LIST2
    WHERE PLT~EXIDV = PALET_NO
  ORDER BY KTD~MATNR KTU~EXIDV.


  LOOP AT GT_LIST2.
    GT_LIST2-BRGEW =  GT_LIST2-BRGEW * GT_LIST2-VEMNG.
    MODIFY GT_LIST2.
  ENDLOOP.


  SELECT KTD~MATNR
         SUM( KTD~VEMNG )    AS TOTAL_KUTU
         COUNT(*)            AS COUNT_KUTU
         PLT~BRGEW AS TOTAL_BRGEW

      FROM VEKP AS PLT
INNER JOIN VEPO AS PLD ON PLT~VENUM = PLD~VENUM
INNER JOIN VEKP AS KTU ON PLD~UNVEL = KTU~VENUM
INNER JOIN VEPO AS KTD ON KTU~VENUM = KTD~VENUM
INNER JOIN MARA AS MAR ON KTD~MATNR = MAR~MATNR
      INTO CORRESPONDING FIELDS OF TABLE GT_LIST1
       WHERE PLT~EXIDV = PALET_NO
  GROUP BY KTD~MATNR PLT~BRGEW
  ORDER BY KTD~MATNR.

ENDFORM.

FORM ALANKATALOGU_OLUSTUR .

  DATA : GS_FIELDCAT  TYPE SLIS_FIELDCAT_ALV.
  GS_FIELDCAT-COL_POS    = 1.
  GS_FIELDCAT-FIELDNAME  = 'LGNUM'.
  GS_FIELDCAT-TABNAME    = 'GT_LIST3'.
  GS_FIELDCAT-SELTEXT_M  = 'DEPO KODU'.
  GS_FIELDCAT-OUTPUTLEN   = 20.
  APPEND GS_FIELDCAT TO GT_FIELDCAT_LIST3.
  GS_FIELDCAT-COL_POS    = 2.
  GS_FIELDCAT-FIELDNAME  = 'DESCRIPTION'.
  GS_FIELDCAT-TABNAME    = 'GT_LIST3'.
  GS_FIELDCAT-SELTEXT_M  = 'AÇIKLAMA'.
  GS_FIELDCAT-OUTPUTLEN   = 20.
  APPEND GS_FIELDCAT TO GT_FIELDCAT_LIST3.
  GS_FIELDCAT-COL_POS    = 3.
  GS_FIELDCAT-FIELDNAME  = 'STATUS'.
  GS_FIELDCAT-TABNAME    = 'GT_LIST3'.
  GS_FIELDCAT-SELTEXT_M  = 'DURUM'.
  GS_FIELDCAT-OUTPUTLEN   = 20.
  APPEND GS_FIELDCAT TO GT_FIELDCAT_LIST3.
  GS_FIELDCAT-COL_POS    = 4.
  GS_FIELDCAT-FIELDNAME  = 'PLT_NO'.
  GS_FIELDCAT-TABNAME    = 'GT_LIST3'.
  GS_FIELDCAT-SELTEXT_M  = 'PALET NO'.
  GS_FIELDCAT-OUTPUTLEN   = 20.
  APPEND GS_FIELDCAT TO GT_FIELDCAT_LIST3.

  GS_FIELDCAT-COL_POS    = 1.
  GS_FIELDCAT-FIELDNAME  = 'MATNR'.
  GS_FIELDCAT-TABNAME    = 'GT_LIST1'.
  GS_FIELDCAT-SELTEXT_M  = 'MALZEME NUMARASI'.
  GS_FIELDCAT-OUTPUTLEN   = 20.
  APPEND GS_FIELDCAT TO GT_FIELDCAT_LIST1.
  GS_FIELDCAT-COL_POS    = 2.
  GS_FIELDCAT-FIELDNAME  = 'COUNT_KUTU'.
  GS_FIELDCAT-TABNAME    = 'GT_LIST1'.
  GS_FIELDCAT-SELTEXT_M  = 'KUTU SAYISI.'.
  GS_FIELDCAT-OUTPUTLEN   = 20.
  APPEND GS_FIELDCAT TO GT_FIELDCAT_LIST1.
  GS_FIELDCAT-COL_POS    = 3.
  GS_FIELDCAT-FIELDNAME  = 'TOTAL_KUTU'.
  GS_FIELDCAT-TABNAME    = 'GT_LIST1'.
  GS_FIELDCAT-SELTEXT_M  = 'TOPLAM MİKTAR.'.
  GS_FIELDCAT-OUTPUTLEN   = 20.
  APPEND GS_FIELDCAT TO GT_FIELDCAT_LIST1.
  GS_FIELDCAT-COL_POS    = 4.
  GS_FIELDCAT-FIELDNAME  = 'TOTAL_BRGEW'.
  GS_FIELDCAT-TABNAME    = 'GT_LIST1'.
  GS_FIELDCAT-SELTEXT_M  = 'TOPLAM KG'.
  GS_FIELDCAT-OUTPUTLEN   = 20.
  APPEND GS_FIELDCAT TO GT_FIELDCAT_LIST1.

  GS_FIELDCAT-COL_POS    = 1.
  GS_FIELDCAT-FIELDNAME  = 'EXIDV'.
  GS_FIELDCAT-TABNAME    = 'GT_LIST2'.
  GS_FIELDCAT-SELTEXT_M  = 'TB'.
  GS_FIELDCAT-OUTPUTLEN   = 20.
  APPEND GS_FIELDCAT TO GT_FIELDCAT_LIST2.
  GS_FIELDCAT-COL_POS    = 2.
  GS_FIELDCAT-FIELDNAME  = 'MATNR'.
  GS_FIELDCAT-TABNAME    = 'GT_LIST2'.
  GS_FIELDCAT-SELTEXT_M  = 'MALZEME.'.
  GS_FIELDCAT-OUTPUTLEN   = 20.
  APPEND GS_FIELDCAT TO GT_FIELDCAT_LIST2.
  GS_FIELDCAT-COL_POS    = 3.
  GS_FIELDCAT-FIELDNAME  = 'VEMNG'.
  GS_FIELDCAT-TABNAME    = 'GT_LIST2'.
  GS_FIELDCAT-SELTEXT_M  = 'KUTU İÇİ ADET'.
  GS_FIELDCAT-OUTPUTLEN   = 20.
  APPEND GS_FIELDCAT TO GT_FIELDCAT_LIST2.
  GS_FIELDCAT-COL_POS    = 4.
  GS_FIELDCAT-FIELDNAME  = 'BRGEW'.
  GS_FIELDCAT-TABNAME    = 'GT_LIST2'.
  GS_FIELDCAT-SELTEXT_M  = 'KG'.
  GS_FIELDCAT-OUTPUTLEN   = 20.
  APPEND GS_FIELDCAT TO GT_FIELDCAT_LIST2.
  GS_FIELDCAT-COL_POS    = 5.
  GS_FIELDCAT-FIELDNAME  = 'AENAM'.
  GS_FIELDCAT-TABNAME    = 'GT_LIST2'.
  GS_FIELDCAT-SELTEXT_M  = 'KİŞİ'.
  GS_FIELDCAT-OUTPUTLEN   = 20.
  APPEND GS_FIELDCAT TO GT_FIELDCAT_LIST2.
  GS_FIELDCAT-COL_POS    = 6.
  GS_FIELDCAT-FIELDNAME  = 'AEDAT'.
  GS_FIELDCAT-TABNAME    = 'GT_LIST2'.
  GS_FIELDCAT-SELTEXT_M  = 'TARİH'.
  GS_FIELDCAT-OUTPUTLEN   = 20.
  APPEND GS_FIELDCAT TO GT_FIELDCAT_LIST2.

ENDFORM. " ALANKATALOGU_OLUSTUR


FORM TABLOLARI_GOSTER .

  DATA : LV_REPID  TYPE SY-REPID,
         LS_LAYOUT TYPE SLIS_LAYOUT_ALV,
         LT_EVENTS TYPE SLIS_T_EVENT.
  LV_REPID = SY-REPID.
  CALL FUNCTION 'REUSE_ALV_BLOCK_LIST_INIT'
    EXPORTING
      I_CALLBACK_PROGRAM = LV_REPID.
  CALL FUNCTION 'REUSE_ALV_BLOCK_LIST_APPEND'
    EXPORTING
      IS_LAYOUT                  = LS_LAYOUT
      IT_FIELDCAT                = GT_FIELDCAT_LIST3
      I_TABNAME                  = 'GT_LIST3'
      IT_EVENTS                  = LT_EVENTS
    TABLES
      T_OUTTAB                   = GT_LIST3
    EXCEPTIONS
      PROGRAM_ERROR              = 1
      MAXIMUM_OF_APPENDS_REACHED = 2
      OTHERS                     = 3.
  CALL FUNCTION 'REUSE_ALV_BLOCK_LIST_APPEND'
    EXPORTING
      IS_LAYOUT                  = LS_LAYOUT
      IT_FIELDCAT                = GT_FIELDCAT_LIST1
      I_TABNAME                  = 'GT_LIST1'
      IT_EVENTS                  = LT_EVENTS
    TABLES
      T_OUTTAB                   = GT_LIST1
    EXCEPTIONS
      PROGRAM_ERROR              = 1
      MAXIMUM_OF_APPENDS_REACHED = 2
      OTHERS                     = 3.

  CALL FUNCTION 'REUSE_ALV_BLOCK_LIST_APPEND'
    EXPORTING
      IS_LAYOUT                  = LS_LAYOUT
      IT_FIELDCAT                = GT_FIELDCAT_LIST2
      I_TABNAME                  = 'GT_LIST2'
      IT_EVENTS                  = LT_EVENTS
    TABLES
      T_OUTTAB                   = GT_LIST2
    EXCEPTIONS
      PROGRAM_ERROR              = 1
      MAXIMUM_OF_APPENDS_REACHED = 2
      OTHERS                     = 3.

  CALL FUNCTION 'REUSE_ALV_BLOCK_LIST_DISPLAY'
    EXCEPTIONS
      PROGRAM_ERROR = 1
      OTHERS        = 2.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
    WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

ENDFORM.                    " TABLOLARI_GOSTER
