*&---------------------------------------------------------------------*
*& Report  Z_PALET_ICERIK
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
 
REPORT Z_PALET_ICERIK.
 
TYPE-POOLS: SLIS.
 
TABLES : VEKP, VEPO, LQUA, VEVW.
 
DATA: FIELDCATALOG TYPE SLIS_T_FIELDCAT_ALV WITH HEADER LINE.
DATA: IT_FIELDCAT  TYPE LVC_T_FCAT,     "slis_t_fieldcat_alv WITH HEADER LINE,
      WA_FIELDCAT  TYPE LVC_S_FCAT,
      GD_TAB_GROUP TYPE SLIS_T_SP_GROUP_ALV,
      GD_LAYOUT    TYPE LVC_S_LAYO,     "slis_layout_alv,
      GD_REPID     LIKE SY-REPID.
 
SELECTION-SCREEN BEGIN OF BLOCK BLK1. "seçim kriterleri
SELECT-OPTIONS: PALET_NO FOR VEKP-EXIDV .
SELECT-OPTIONS: DEPO_KOD FOR LQUA-LGNUM .
SELECT-OPTIONS: MLZME_NO FOR VEPO-MATNR .
SELECT-OPTIONS: KUTU_NO FOR VEPO-UNVEL .
SELECTION-SCREEN END OF BLOCK BLK1.
 
DATA : BEGIN OF GT_PALET OCCURS 0 ,
 
         EXIDV LIKE VEKP-EXIDV,
         LGNUM LIKE LQUA-LGNUM,
         MATNR LIKE VEPO-MATNR,
         UNVEL LIKE VEPO-UNVEL,
         BRGEW LIKE VEKP-BRGEW,
         TARAG LIKE VEKP-TARAG,
         VEMNG LIKE VEPO-VEMNG,
         " HANDLE LIKE VEVW-HANDLE,
         VENUM LIKE VEKP-VENUM,
         KUTU  LIKE VEKP-EXIDV,
 
       END OF GT_PALET.
 
DATA : BEGIN OF GT_VEKP OCCURS 0 ,  "internal table
 
         EXIDV LIKE VEKP-EXIDV,  "palet no
         VENUM LIKE VEKP-VENUM,  "TAŞIMA BİRİMİ NUMARASI
         VHART LIKE VEKP-VHART,   "PALET
       END OF GT_VEKP.
 
DATA : BEGIN OF GT_VEPO OCCURS 0 ,  "internal table
 
         MATNR LIKE VEPO-MATNR,  "malzeme no
         UNVEL LIKE VEPO-UNVEL,  "kutu no
         VENUM LIKE VEPO-VENUM,  "TAŞIMA BİRİMİ NUMARASI
       END OF GT_VEPO.
 
DATA : BEGIN OF GT_LIST OCCURS 0 ,  "internal table
 
         UNVEL LIKE VEPO-UNVEL,  "ALT DÜZEY TAŞIMA BİRİMİ NUMARASI
         EXIDV LIKE VEKP-EXIDV,  "kutu no
         VENUM LIKE VEPO-VENUM,
         MATNR LIKE VEPO-MATNR,  "malzeme no
 
       END OF GT_LIST.
 
PERFORM GET_DATA.
PERFORM BUILD_FIELDCATALOG.
PERFORM BUILD_LAYOUT.
PERFORM DISPLAY_ALV_REPORT.
 
FORM GET_DATA .
 
  SELECT * FROM VEPO INTO CORRESPONDING FIELDS OF TABLE GT_VEPO.
  SELECT * FROM VEKP INTO CORRESPONDING FIELDS OF TABLE GT_VEKP.
 
  SELECT *
 INTO CORRESPONDING FIELDS OF TABLE GT_PALET
     FROM VEPO
 INNER JOIN VEKP ON VEKP~VENUM = VEPO~VENUM AND VEKP~VHART = 'ZPAL'
   WHERE EXIDV IN PALET_NO
    AND LGNUM IN DEPO_KOD
    AND MATNR IN MLZME_NO
    AND UNVEL IN KUTU_NO.
 
  SELECT *
 INTO CORRESPONDING FIELDS OF TABLE GT_LIST
     FROM VEPO
 INNER JOIN VEKP ON VEKP~VENUM = VEPO~UNVEL
    WHERE VEPO~UNVEL <> ''.
 
  LOOP AT GT_LIST.
 
    IF GT_LIST-VENUM <> ''.
      READ TABLE GT_VEPO WITH KEY VENUM = GT_LIST-VENUM.
      IF SY-SUBRC = 0.
 
        GT_LIST-MATNR = GT_VEPO-MATNR.
 
      ENDIF.
      MODIFY GT_LIST.
    ENDIF.
  ENDLOOP.
 
  LOOP AT GT_PALET.
    IF GT_PALET-UNVEL <> ''.
      READ TABLE GT_LIST WITH KEY UNVEL = GT_PALET-UNVEL.
      IF SY-SUBRC = 0.
 
        GT_PALET-KUTU = GT_LIST-EXIDV.
        GT_PALET-MATNR = GT_LIST-MATNR.
 
      ENDIF.
      MODIFY GT_PALET.
    ENDIF.
  ENDLOOP.
 
ENDFORM.
 
 
FORM BUILD_FIELDCATALOG . " listede görüntülenecek olanlar
 
  WA_FIELDCAT-FIELDNAME   = 'exidv'. "palet_no
  WA_FIELDCAT-SCRTEXT_M   = TEXT-001.
  FIELDCATALOG-OUTPUTLEN   = 20.
  WA_FIELDCAT-COL_POS     = 1.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.
 
  WA_FIELDCAT-FIELDNAME   = 'LGNUM'.
  WA_FIELDCAT-SCRTEXT_M   = TEXT-002. "depo_kodu
  FIELDCATALOG-OUTPUTLEN   = 20.
  WA_FIELDCAT-COL_POS     = 2.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.
 
  WA_FIELDCAT-FIELDNAME   = 'MATNR'.
  WA_FIELDCAT-SCRTEXT_M   = TEXT-003. "malzeme_no
  FIELDCATALOG-OUTPUTLEN   = 20.
  WA_FIELDCAT-COL_POS     = 3.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.
 
  WA_FIELDCAT-FIELDNAME   = 'UNVEL'.
  WA_FIELDCAT-SCRTEXT_M   = TEXT-004. "alt düzey tb
  FIELDCATALOG-OUTPUTLEN   = 20.
  WA_FIELDCAT-COL_POS     = 4.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.
 
  WA_FIELDCAT-FIELDNAME   = 'BRGEW'.
  WA_FIELDCAT-SCRTEXT_M   = TEXT-005. "toplam_agirlik
  FIELDCATALOG-OUTPUTLEN   = 20.
  WA_FIELDCAT-COL_POS     = 5.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.
 
  WA_FIELDCAT-FIELDNAME   = 'TARAG'.
  WA_FIELDCAT-SCRTEXT_M   = TEXT-006. "dara
  FIELDCATALOG-OUTPUTLEN   = 10.
  WA_FIELDCAT-COL_POS     = 6.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.
 
  WA_FIELDCAT-FIELDNAME   = 'VEMNG'.
  WA_FIELDCAT-SCRTEXT_M   = TEXT-007. "miktar
  FIELDCATALOG-OUTPUTLEN   = 20.
  WA_FIELDCAT-COL_POS     = 7.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.
 
*  WA_FIELDCAT-FIELDNAME   = 'HANDLE'.
*  WA_FIELDCAT-SCRTEXT_M   = TEXT-008. "obje_no
*  FIELDCATALOG-OUTPUTLEN   = 20.
*  WA_FIELDCAT-COL_POS     = 8.
*  APPEND WA_FIELDCAT TO IT_FIELDCAT.
*  CLEAR  WA_FIELDCAT.
 
  WA_FIELDCAT-FIELDNAME   = 'KUTU'.
  WA_FIELDCAT-SCRTEXT_M   = TEXT-009. "kutu_no
  FIELDCATALOG-OUTPUTLEN   = 20.
  WA_FIELDCAT-COL_POS     = 9.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.
 
 
  WA_FIELDCAT-FIELDNAME   = 'venum'.
  WA_FIELDCAT-SCRTEXT_M   = TEXT-010. "venum_no
  FIELDCATALOG-OUTPUTLEN   = 20.
  WA_FIELDCAT-COL_POS     = 10.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.
 
ENDFORM.                    " BUILD_FIELDCATALOG
 
FORM BUILD_LAYOUT .
 
  GD_LAYOUT-STYLEFNAME = 'FIELD_STYLE'.
  GD_LAYOUT-ZEBRA      = 'X'.
  GD_LAYOUT-CWIDTH_OPT = 'X'.
 
ENDFORM.                    " BUILD_LAYOUT
 
FORM DISPLAY_ALV_REPORT .
  GD_REPID = SY-REPID.
 
  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY_LVC'
    EXPORTING
      I_CALLBACK_PROGRAM      = GD_REPID
      I_CALLBACK_USER_COMMAND = 'USER_COMMAND'
      IS_LAYOUT_LVC           = GD_LAYOUT
      IT_FIELDCAT_LVC         = IT_FIELDCAT
      I_SAVE                  = 'X'
    TABLES
      T_OUTTAB                = GT_PALET
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
ENDFORM.                    " DISPLAY_ALV_REPORT
 
"search help
 
 
DATA: BEGIN OF LT_UNVEL OCCURS 0,
        UNVEL LIKE VEPO-UNVEL,
      END OF LT_UNVEL.
 
AT SELECTION-SCREEN ON VALUE-REQUEST FOR  : KUTU_NO-LOW.
  PERFORM KUTU_SEARCHHELP.
 
INITIALIZATION.
  PERFORM INIT_SELECTION.
 
AT SELECTION-SCREEN ON VALUE-REQUEST FOR  : KUTU_NO-HIGH.
  PERFORM KUTU_SEARCHHELP.
 
INITIALIZATION.
  PERFORM INIT_SELECTION.
FORM KUTU_SEARCHHELP .
 
  CALL FUNCTION 'F4IF_INT_TABLE_VALUE_REQUEST'
    EXPORTING
      RETFIELD        = 'unvel'
      DYNPPROG        = SY-CPROG
      DYNPNR          = SY-DYNNR
      DYNPROFIELD     = 'KUTU_NO'
      VALUE_ORG       = 'S'
      WINDOW_TITLE    = 'Kutu Arama'
    TABLES
      VALUE_TAB       = LT_UNVEL[]
    EXCEPTIONS
      PARAMETER_ERROR = 1
      NO_VALUES_FOUND = 2
      OTHERS          = 3.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
    WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF. "   IF sy-subrc <> 0.
 
ENDFORM.                    " KUTU_SEARCHHELP
 
FORM INIT_SELECTION .
 
  SELECT DISTINCT UNVEL FROM VEPO
  INTO CORRESPONDING FIELDS OF TABLE
  LT_UNVEL.
ENDFORM.                    " INIT_SELECTION
