REPORT Z_TESLIMAT_ONERI.

TABLES : ZWM_T_SEVK_EMRI , LQUA, VEPO, ZWM_T_RAFSORUMLU, VEKP, MARM.

TYPE-POOLS: SLIS.

DATA : BEGIN OF GT_LIST OCCURS 0 ,
         BOLGE       LIKE ZWM_T_RAFSORUMLU-RAFBOLGE,
         SAMPA_NO    LIKE ZWM_T_SEVK_EMRI-MATNR,
         RAF_NO      LIKE ZWM_T_SEVK_EMRI-LGPLA,
         ONERILEN_AD LIKE ZWM_T_SEVK_EMRI-MENGE,
         OTB         LIKE ZWM_T_SEVK_EMRI-MENGE,
         OKUNAN_AD   LIKE ZWM_T_SEVK_EMRI-OKUNAN,
         CTB         LIKE ZWM_T_SEVK_EMRI-OKUNAN,
         RAF_STOK    LIKE LQUA-VERME,
         FARK        LIKE ZWM_T_SEVK_EMRI-OKUNAN,
         KALAN_ADET  LIKE ZWM_T_SEVK_EMRI-OKUNAN,
         KIADET      LIKE MARM-UMREZ,
         TESLIMAT    LIKE ZWM_T_SEVK_EMRI-VBELN,
       END OF GT_LIST.

DATA : BEGIN OF GT_RAF OCCURS 0 ,
         RAFBOLGE    LIKE ZWM_T_RAFSORUMLU-RAFBOLGE,
         LGPLA_FIRST LIKE ZWM_T_RAFSORUMLU-LGPLA_FIRST,
         LGPLA_LAST  LIKE ZWM_T_RAFSORUMLU-LGPLA_LAST,
       END OF GT_RAF.


DATA: FIELDCATALOG TYPE SLIS_T_FIELDCAT_ALV WITH HEADER LINE.

DATA: IT_FIELDCAT  TYPE LVC_T_FCAT,
      WA_FIELDCAT  TYPE LVC_S_FCAT,
      GD_TAB_GROUP TYPE SLIS_T_SP_GROUP_ALV,
      GD_LAYOUT    TYPE LVC_S_LAYO,
      GD_REPID     LIKE SY-REPID.

SELECTION-SCREEN BEGIN OF BLOCK BLOCK1 WITH FRAME
                                     TITLE TEXT-001.
PARAMETER: TSLMT_NO TYPE LQUA-VBELN .
PARAMETER: GD_UCOMM LIKE SY-UCOMM DEFAULT 'BUT1' NO-DISPLAY.

SELECTION-SCREEN END OF BLOCK BLOCK1.

PERFORM GET_DATA.
PERFORM BUILD_FIELDCATALOG.
PERFORM BUILD_LAYOUT.
PERFORM DISPLAY_ALV_REPORT.

FORM GET_DATA .

  SELECT ZR~RAFBOLGE
         ZR~LGPLA_LAST
         ZR~LGPLA_FIRST
    FROM ZWM_T_RAFSORUMLU AS ZR
    INTO CORRESPONDING FIELDS OF TABLE GT_RAF.

  SELECT   Z~MATNR   AS SAMPA_NO           "SAMPA NO
           Z~LGPLA   AS RAF_NO             "RAF NO
           Z~MENGE   AS ONERILEN_AD        "ÖNERİLEN AD
           Z~MENGE   AS OTB                "ÖNERİLEN TAŞIMA BİRİMİ ADETİ=ONERİLENADET/K.İADET
           Z~OKUNAN  AS OKUNAN_AD          "OKUNAN adet
           Z~OKUNAN  AS CTB                "ÇEKİLEN TAŞIMA BİRİMİ ADET=OKUNAN/K.İ.ADET
           Z~OKUNAN  AS FARK               "FARK (TAŞIMA BİRİM)
           Z~OKUNAN  AS KALAN_ADET         "KALAN ADET=MENGE-OKUNAN    RAF_STOK    LIKE LQUA-VERME,
           SUM( L~VERME )  AS RAF_STOK
           M~UMREZ   AS KIADET             "kutu içi adet
           Z~VBELN   AS TESLIMAT            "teslimat numarası
          " ZR~RAFBOLGE AS BOLGE            "bölge
      FROM   ZWM_T_SEVK_EMRI AS Z
    INNER JOIN MARM AS M ON M~MATNR = Z~MATNR AND M~MEINH = 'KTU'
    INNER JOIN LQUA AS L ON L~MATNR = Z~MATNR
   " INNER JOIN ZWM_T_RAFSORUMLU AS ZR ON ZR~LGPLA_LAST = Z~LGPLA
    INTO CORRESPONDING FIELDS OF TABLE GT_LIST
       WHERE Z~VBELN = TSLMT_NO
    GROUP BY Z~MATNR Z~LGPLA  Z~MENGE Z~MENGE Z~OKUNAN Z~OKUNAN
        Z~OKUNAN Z~OKUNAN  M~UMREZ   Z~VBELN Z~LGNUM. "ZR~RAFBOLGE
   "ORDER BY ZR~RAFBOLGE.

  LOOP AT GT_LIST.

    GT_LIST-OTB = GT_LIST-ONERILEN_AD / GT_LIST-KIADET.
    GT_LIST-CTB = GT_LIST-OKUNAN_AD / GT_LIST-KIADET.
    GT_LIST-FARK = GT_LIST-OTB - GT_LIST-CTB.
    GT_LIST-KALAN_ADET = GT_LIST-ONERILEN_AD - GT_LIST-OKUNAN_AD.

    MODIFY GT_LIST.

          LOOP AT GT_RAF.

      IF GT_LIST-RAF_NO BETWEEN GT_RAF-LGPLA_FIRST AND GT_RAF-LGPLA_LAST .

        GT_LIST-BOLGE = GT_RAF-RAFBOLGE.

        MODIFY GT_LIST.


      ENDIF.

    ENDLOOP.

  ENDLOOP.

ENDFORM.

FORM BUILD_FIELDCATALOG . " listede görüntülenecek olanlar

  WA_FIELDCAT-FIELDNAME   = 'BOLGE'.
  WA_FIELDCAT-SCRTEXT_M   = 'BOLGE'."TEXT-009.
  FIELDCATALOG-OUTPUTLEN   = 20.
  WA_FIELDCAT-COL_POS     = 1.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'SAMPA_NO'.
  WA_FIELDCAT-SCRTEXT_M   = 'SAMPA_NO'."TEXT-001.
  FIELDCATALOG-OUTPUTLEN   = 15.
  WA_FIELDCAT-COL_POS     = 2.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'RAF_NO'.
  WA_FIELDCAT-SCRTEXT_M   = 'RAF_NO'."TEXT-002.
  FIELDCATALOG-OUTPUTLEN   = 15.
  WA_FIELDCAT-COL_POS     = 3.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'RAF_STOK'.
  WA_FIELDCAT-SCRTEXT_M   = 'RAF_STOK'."TEXT-003.
  FIELDCATALOG-OUTPUTLEN   = 15.
  WA_FIELDCAT-COL_POS     = 4.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'ONERILEN_AD'.
  WA_FIELDCAT-SCRTEXT_M   = 'ONERILEN_AD'."TEXT-004.
  FIELDCATALOG-OUTPUTLEN   = 15.
  WA_FIELDCAT-COL_POS     = 5.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'OTB'.
  WA_FIELDCAT-SCRTEXT_M   = 'ÖNERİLEN TAŞIMA BİRİMİ ADETİ'."TEXT-005.
  FIELDCATALOG-OUTPUTLEN   = 20.
  WA_FIELDCAT-COL_POS     = 6.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'CTB'.
  WA_FIELDCAT-SCRTEXT_M   = 'ÇEKİLEN TAŞIMA BİRİMİ ADET'."TEXT-006.
  FIELDCATALOG-OUTPUTLEN   = 20.
  WA_FIELDCAT-COL_POS     = 7.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'FARK'.
  WA_FIELDCAT-SCRTEXT_M   = 'FARK'."TEXT-007.
  FIELDCATALOG-OUTPUTLEN   = 15.
  WA_FIELDCAT-COL_POS     = 8.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME   = 'KALAN_ADET'.
  WA_FIELDCAT-SCRTEXT_M   = 'KALAN_ADET'."TEXT-008.
  FIELDCATALOG-OUTPUTLEN   = 15.
  WA_FIELDCAT-COL_POS     = 9.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR  WA_FIELDCAT.

ENDFORM.                    " BUILD_FIELDCATALOG

FORM BUILD_LAYOUT .

  GD_LAYOUT-STYLEFNAME = 'FIELD_STYLE'.
  GD_LAYOUT-ZEBRA      = 'X'.
  GD_LAYOUT-CWIDTH_OPT = 'X'.

ENDFORM.                    " BUILD_LAYOUT

FORM DISPLAY_ALV_REPORT .
  GD_REPID = SY-REPID.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY_LVC'
    EXPORTING
      I_CALLBACK_PROGRAM      = GD_REPID
      I_CALLBACK_USER_COMMAND = 'USER_COMMAND'
      IS_LAYOUT_LVC           = GD_LAYOUT
      IT_FIELDCAT_LVC         = IT_FIELDCAT
      I_SAVE                  = 'X'
    TABLES
      T_OUTTAB                = GT_LIST
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.

  ENDIF.
ENDFORM.                    " DISPLAY_ALV_REPORT
